### ISSUE TITLE
No Issue just a question

### ISSUE THREAD

**Issue by Alexis-Grimm** [isuke/vscode-advanced-poe-filter#3]
I really just wanted to say just how much i love filter of kalandra and advanced poe filter, i find that filtration is very buggy, and filterblade doesnt have quite enough control, but this is quite literally perfect for my uses, Thank you so much for this. Now for the question

Basically i was just wondering if there were any way to declare variables in the script itself, or at least copy variables into a text file, because i work on two different computers and fleshing out all the variables multiple times is rather tedious, if there isn't then are there any plans to?
Once again thank you so much for this.

**Comment by isuke** [comment]
Thank you for using and love my app, and sorry for the late reply.

About for your question, you can use export to Json and import.
You can export/import the entire filter or just variables.

I don't think more for now.
If you have an idea, please tell me.

Thank you.
