### ISSUE TITLE
Importing Files in Firefox

### ISSUE THREAD

**Issue by Alexis-Grimm** [isuke/vscode-advanced-poe-filter#4]
Hello, i do not seem to be able to import files in firefox, it works fine in chrome but whenever I press any of the import buttons in firefox nothing happens, even the buttons for importing default colors.

**Comment by isuke** [comment]
Is it about Filter of Kalandra (not Visual Studio Code Extension)?

I'll investigate immediately.

Sorry for the late reply.
Thank you.

**Comment by isuke** [comment]
Please see https://filter-of-kalandra-doc.netlify.com/usage/#attention-when-using-with-firefox
